[package]
name = "olcJamRust"
version = "0.1.0"
authors = ["lukecashwell <lukecashwell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.11.2"
png = "0.15.0"
rand = "*"